version: "3"

services:
  app:
    image: IMAGE_GOES_HERE
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/app:/var/www/html/storage/app
      - /home/ubuntu/content:/var/www/html/themes/app/content
      - /home/ubuntu/meta:/var/www/html/themes/app/meta
      - /etc/ssl:/etc/ssl
      - /home/ubuntu/ftp:/var/www/html/ftp
  cron:
    image: IMAGE_GOES_HERE
    volumes:
      - /home/ubuntu/app:/var/www/html/storage/app
      - /home/ubuntu/content:/var/www/html/themes/app/content
      - /home/ubuntu/meta:/var/www/html/themes/app/meta
      - /etc/ssl:/etc/ssl
      - /home/ubuntu/cron.sh:/var/www/html/cron.sh
      - /home/ubuntu/ftp:/var/www/html/ftp
    command: sh cron.sh
