version: "3"

services:

  app:
    image: IMAGE_GOES_HERE
    restart: always
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/app:/var/www/html/storage/app
      - /home/ubuntu/content:/var/www/html/themes/app/content
      - /home/ubuntu/meta:/var/www/html/themes/app/meta
      - /etc/ssl:/etc/ssl

  cron:
    image: IMAGE_GOES_HERE
    volumes:
      - /home/ubuntu/app:/var/www/html/storage/app
      - /home/ubuntu/content:/var/www/html/themes/app/content
      - /home/ubuntu/meta:/var/www/html/themes/app/meta
      - /etc/ssl:/etc/ssl
      - /home/ubuntu/cron.sh:/var/www/html/cron.sh
    command: sh cron.sh

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'SITE_DOMAIN_GOES_HERE'
      SITES: 'SITE_DOMAIN_GOES_HERE=app:80'

volumes:
  ssl_data: