version: "3"

services:
  app:
    image: IMAGE_GOES_HERE
    restart: always
    networks:
      - sdnet
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/app:/var/www/html/storage/app
      - /home/ubuntu/content:/var/www/html/themes/app/content
      - /home/ubuntu/meta:/var/www/html/themes/app/meta
      - /etc/ssl:/etc/ssl

  cron:
    image: IMAGE_GOES_HERE
    volumes:
      - /home/ubuntu/app:/var/www/html/storage/app
      - /home/ubuntu/content:/var/www/html/themes/app/content
      - /home/ubuntu/meta:/var/www/html/themes/app/meta
      - /etc/ssl:/etc/ssl
      - /home/ubuntu/cron.sh:/var/www/html/cron.sh
    command: sh cron.sh

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
    restart: always
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - sdnet
    ports:
      - 9200:9200
      - 9300:9300

networks:
  sdnet:
    driver: bridge