version: "3"

services:
  app:
    image: IMAGE_GOES_HERE
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/app:/var/www/html/storage/app
      - /home/ubuntu/content:/var/www/html/themes/app/content
      - /home/ubuntu/meta:/var/www/html/themes/app/meta
      - /etc/ssl:/etc/ssl
  cron:
    image: IMAGE_GOES_HERE
    volumes:
      - /home/ubuntu/app:/var/www/html/storage/app
      - /home/ubuntu/content:/var/www/html/themes/app/content
      - /home/ubuntu/meta:/var/www/html/themes/app/meta
      - /etc/ssl:/etc/ssl
      - /home/ubuntu/cron.sh:/var/www/html/cron.sh
    command: sh cron.sh
  redis:
    image: redis:alpine
    command: redis-server --requirepass "${REDIS_PASSWORD}" --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - /home/ubuntu/redis_data:/var/lib/redis
      - /home/ubuntu/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - sdnet
    environment:
      - REDIS_REPLICATION_MODE=master